version=0.4.0
buildNumber=10

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g

#Gradle
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true