version=0.13.0
buildNumber=21

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx12g -XX:MaxMetaspaceSize=2g

#Gradle
org.gradle.jvmargs=-Xmx12g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
