[versions]
# Gradle
agp = "9.2.1"
android-compileSdk = "36"
android-minSdk = "30"
android-targetSdk = "36"

# Google
googleServices = "4.4.4"
googleFirebaseBom = "34.13.0"
googleGms = "21.6.0"
googleId = "1.2.0"

# Android
androidxCore = "1.18.0"
androidxAppcompat = "1.7.1"
androidxActivity = "1.13.0"
androidxTestExt = "1.3.0"
androidxTestEspresso = "3.7.0"
androidxLifecycleRuntime = "2.10.0"
androidxComposeBom = "2026.05.01"
androidxCredential = "1.6.0"
androidxXRCompose = "1.0.0-alpha13"
androidxXRRuntime = "1.0.0-alpha13"
androidxXRScenecore = "1.0.0-alpha14"
androidxXRMaterial3 = "1.0.0-alpha16"

# Jetbrains
kotlin = "2.3.21"
kotlinxCoroutines = "1.11.0"
kotlinxSerialization = "1.11.0"
kotlinxDatetime = "0.8.0-0.6.x-compat"
lifecycle = "2.10.0"
navigation = "2.9.2"
composeHotReload = "1.1.1"
composeMultiplatform = "1.11.0"
composeMaterial3 = "1.9.0"
composeMaterial3Adaptive = "1.2.0"
composeMaterial = "1.7.3"
kotlin-wrappers = "2026.5.6"
ktor = "3.5.0"

# Java
junit = "4.13.2"
robolectric = "4.16.1"

# 3rd party
koin = "4.2.1"
gitliveFirebase = "2.4.0"
mirzemehdiKmpAuth = "2.3.1"
kermit = "2.1.0"
buildkonfig = "0.21.2"
coil3 = "3.4.0"
sketch = "4.4.0"

omnifeed = "0.10.0"

[libraries]
# Android
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntime" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidxCredential" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidxCredential" }
androidx-xr-compose = { group = "androidx.xr.compose", name = "compose", version.ref = "androidxXRCompose" }
androidx-xr-runtime = { group = "androidx.xr.runtime", name = "runtime", version.ref = "androidxXRRuntime" }
androidx-xr-scenecore = { group = "androidx.xr.scenecore", name = "scenecore", version.ref = "androidxXRScenecore" }
androidx-xr-material3 = { group = "androidx.xr.compose.material3", name = "material3", version.ref = "androidxXRMaterial3" }

# JetBrains
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "composeMultiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeMaterial" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material3-adaptive-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "composeMaterial3" }
compose-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "composeMaterial3Adaptive" }
kotlin-wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlin-wrappers" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }

# Java
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

# 3rd party
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core"}
koin-compose = { module = "io.insert-koin:koin-compose"}
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel"}
koin-android = { module = "io.insert-koin:koin-android"}
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit"}
touchlab-kermit-test = { module = "co.touchlab:kermit-test", version.ref = "kermit"}
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
panpf-sketch-compose = { module = "io.github.panpf.sketch4:sketch-compose", version.ref = "sketch" }
panpf-sketch-http = { module  = "io.github.panpf.sketch4:sketch-http", version.ref = "sketch"}
panpf-sketch-blurhash = { module = "io.github.panpf.sketch4:sketch-blurhash", version.ref = "sketch" }
gitlive-firebase-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "gitliveFirebase" }
mirzemehdi-kmpauth-google = { group = "io.github.mirzemehdi", name = "kmpauth-google", version.ref = "mirzemehdiKmpAuth"}
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "googleFirebaseBom" }
google-gms-play-service-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googleGms" }
google-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleId" }

# Self
omnifeed = { module = "io.lackstudio.omnifeed:omnifeed", version.ref = "omnifeed" }
omnifeed-core = { module = "io.lackstudio.omnifeed:omnifeed-core", version.ref = "omnifeed" }
omnifeed-unsplash = { module = "io.lackstudio.omnifeed:omnifeed-unsplash", version.ref = "omnifeed" }
omnifeed-ui = { module = "io.lackstudio.omnifeed:omnifeed-ui", version.ref = "omnifeed" }
omnifeed-auth = { module = "io.lackstudio.omnifeed:omnifeed-auth", version.ref = "omnifeed" }

# Test

[plugins]
# Android
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Jetbrains
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# 3rd party
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
